### PR TITLE
Add peer session management and fixes to stabilize downloads

### LINKED ISSUE #64: Torrent peer management
Currently the torrent doesn't do much with the peer sessions it has. This is partly because there is no existing infrastructure for a peer to report its state to its torrent.

This is crucial for a few reasons: if torrent requests peers from its tracker, the peers returned are not guaranteed to be seeds, so the torrent may end up in a situation where it is stuck. Therefore it needs to periodically check (in its "torrent tick") whether we need to disconnect idle peers and request new ones to drive forward the download.

### PR DESCRIPTION
**Pull request by mandreyel**
Closes #64 

**TODO**:
- [x] fix seed/leech entry point: breaks current tests
- [x] fix `peer::state` unit tests

### CODE REVIEW

File: cratetorrent-cli/src/main.rs [hunk 1]
```diff
@@ -85,22 +85,13 @@ fn main() -> Result<(), Box<dyn std::error::Error>> {
...
-    } else {
-        cratetorrent::engine::download_torrent(
-            client_id,
-            download_dir,
-            metainfo,
-            listen_addr,
-            seeds,
-        )?;
-    }
+    cratetorrent::engine::download_torrent(
```
Comment (mandreyel) [inline cratetorrent-cli/src/main.rs:88]: Fix this

File: cratetorrent/src/peer.rs [hunk 2]
```diff
@@ -21,17 +21,32 @@ use tokio::{
...
 use state::*;
 
+pub(crate) use state::{ConnectionState, SessionState};
+
 mod codec;
 mod state;
 #[macro_use]
 mod peer_log;
 
+/// The most essential information of a peer session, dervied from
```
Comment (mandreyel) [inline cratetorrent/src/peer.rs:40]: typo

File: cratetorrent/src/disk.rs [hunk 3]
```diff
@@ -48,13 +48,15 @@ impl DiskHandle {
         id: TorrentId,
         storage_info: StorageInfo,
         piece_hashes: Vec<u8>,
+        sender: torrent::Sender,
```
Comment (mandreyel) [inline cratetorrent/src/disk.rs:51]: In the code everywhere we use `chan` for the variable names of mpsc senders.
